from __future__ import annotations

from uv_stack.config import ConfigRoot
from uv_stack.models import EnvConfig, ResolvedStack
from uv_stack.render import (
    render_environment_yml,
    render_requirements_flat,
    render_requirements_in,
)


def test_render_requirements_in_layered(config_tree: ConfigRoot):
    stack = ResolvedStack(profiles=["ds", "chem"], inline=["umap-learn", "-e /pkg"])
    text = render_requirements_in(stack, config_tree, "main")
    assert "# Generated by uv-stack" in text
    assert f"-r {config_tree.profile_path('ds')}" in text
    assert f"-r {config_tree.profile_path('chem')}" in text
    assert "umap-learn" in text
    assert "-e /pkg" in text
    # main has requirements.local.in in the fixture, so it is referenced
    assert f"-r {config_tree.env_local_path('main')}" in text


def test_render_requirements_in_omits_missing_local(config_tree: ConfigRoot):
    config_tree.env_local_path("main").unlink()
    stack = ResolvedStack(profiles=["ds"])
    text = render_requirements_in(stack, config_tree, "main")
    # The static header always names requirements.local.in, but when the file is
    # absent there must be no -r reference to it and no local-additions section.
    assert "# Environment-local additions" not in text
    assert f"-r {config_tree.env_local_path('main')}" not in text


def test_render_requirements_flat_expands_profiles(config_tree: ConfigRoot):
    stack = ResolvedStack(profiles=["ds", "chem"], inline=["umap-learn"])
    text = render_requirements_flat(stack, config_tree)
    # ds expands to numpy, pandas; chem to rdkit; plus inline umap-learn
    assert "numpy" in text
    assert "pandas" in text
    assert "rdkit" in text
    assert "umap-learn" in text
    # flat form must NOT contain -r references to the config root
    assert "-r " not in text


def test_render_environment_yml():
    env = EnvConfig(name="main", python="3.11", micromamba=["graphviz", "openbabel"])
    text = render_environment_yml(env)
    assert "name: main" in text
    assert "- python=3.11" in text
    assert "- pip" in text
    assert "- graphviz" in text
    assert "- openbabel" in text
    assert "conda-forge" in text


def test_render_environment_yml_appends_extra_channels_after_conda_forge():
    env = EnvConfig(name="main", channels=["bioconda", "mycorp"])
    text = render_environment_yml(env)
    channels = [
        line.strip()[2:] for line in text.splitlines() if line.startswith("  - ")
    ]
    # conda-forge keeps top priority; extras follow in order.
    assert channels[:3] == ["conda-forge", "bioconda", "mycorp"]


def test_render_environment_yml_dedupes_conda_forge():
    env = EnvConfig(name="main", channels=["conda-forge", "bioconda"])
    text = render_environment_yml(env)
    assert text.count("- conda-forge") == 1
    channels = [
        line.strip()[2:] for line in text.splitlines() if line.startswith("  - ")
    ]
    assert channels[:2] == ["conda-forge", "bioconda"]
