from __future__ import annotations

import pytest

from uv_stack.config import ConfigRoot
from uv_stack.errors import ConfigError
from uv_stack.models import EnvConfig, ResolvedStack
from uv_stack.render import (
    render_environment_yml,
    render_requirements_in,
)
from uv_stack.variables import Variables


def test_render_requirements_in_expands_profiles_inline(config_tree: ConfigRoot):
    stack = ResolvedStack(profiles=["ds", "chem"], inline=["umap-learn", "-e /pkg"])
    text = render_requirements_in(stack, config_tree, "main", None)
    assert "# Generated by uv-stack" in text
    assert "# Profile: ds" in text
    assert "numpy" in text
    assert "pandas" in text
    assert "rdkit" in text
    assert f"-r {config_tree.profile_path('ds')}" not in text
    assert "umap-learn" in text
    assert "-e /pkg" in text
    assert f"-r {config_tree.env_local_path('main')}" in text


def test_render_requirements_in_omits_missing_local(config_tree: ConfigRoot):
    config_tree.env_local_path("main").unlink()
    stack = ResolvedStack(profiles=["ds"])
    text = render_requirements_in(stack, config_tree, "main", None)
    # The static header always names requirements.local.in, but when the file is
    # absent there must be no -r reference to it and no local-additions section.
    assert "# Environment-local additions" not in text
    assert f"-r {config_tree.env_local_path('main')}" not in text


def test_render_environment_yml():
    env = EnvConfig(name="main", python="3.11", micromamba=["graphviz", "openbabel"])
    text = render_environment_yml(env)
    assert "name: main" in text
    assert "- python=3.11" in text
    assert "- pip" in text
    assert "- graphviz" in text
    assert "- openbabel" in text
    assert "conda-forge" in text


def test_render_environment_yml_appends_extra_channels_after_conda_forge():
    env = EnvConfig(name="main", channels=["bioconda", "mycorp"])
    text = render_environment_yml(env)
    channels = [
        line.strip()[2:] for line in text.splitlines() if line.startswith("  - ")
    ]
    # conda-forge keeps top priority; extras follow in order.
    assert channels[:3] == ["conda-forge", "bioconda", "mycorp"]


def test_render_environment_yml_dedupes_conda_forge():
    env = EnvConfig(name="main", channels=["conda-forge", "bioconda"])
    text = render_environment_yml(env)
    assert text.count("- conda-forge") == 1
    channels = [
        line.strip()[2:] for line in text.splitlines() if line.startswith("  - ")
    ]
    assert channels[:2] == ["conda-forge", "bioconda"]


def test_render_environment_yml_dedupes_redundant_pip():
    # ``pip`` is always emitted; listing it (or any repeat) in micromamba.txt
    # must not produce a duplicate dependency line.
    env = EnvConfig(name="main", micromamba=["pip", "graphviz", "graphviz"])
    text = render_environment_yml(env)
    assert text.count("- pip") == 1
    assert text.count("- graphviz") == 1


def test_render_expands_references_when_variables_are_supplied(config_tree: ConfigRoot):
    config_tree.profile_path("dev").write_text("includes:\n  - -e ${DEV}/mypkg\n")
    stack = ResolvedStack(profiles=["dev"], inline=["-e ${DEV}/other"])
    variables = Variables(declared=("DEV",), values={"DEV": "/home/me/code"})
    text = render_requirements_in(stack, config_tree, "main", variables)
    assert "-e /home/me/code/mypkg" in text
    assert "-e /home/me/code/other" in text
    assert "${DEV}" not in text


def test_render_leaves_references_literal_when_variables_is_none(config_tree: ConfigRoot):
    stack = ResolvedStack(profiles=[], inline=["-e ${DEV}/other"])
    text = render_requirements_in(stack, config_tree, "main", None)
    assert "-e ${DEV}/other" in text


def test_render_reports_every_offender_across_profile_and_inline(config_tree: ConfigRoot):
    config_tree.profile_path("dev").write_text("includes:\n  - -e ${A}/x\n")
    stack = ResolvedStack(profiles=["dev"], inline=["-e ${B}/y"])
    with pytest.raises(ConfigError) as excinfo:
        render_requirements_in(stack, config_tree, "main", Variables((), {}))
    assert "A" in excinfo.value.message
    assert "B" in excinfo.value.message


def test_render_output_is_unchanged_for_a_stack_without_references(
    config_tree: ConfigRoot,
):
    """Expansion is a no-op on a stack that references nothing.

    Anchored to the rendered text as well: on its own the equality is a
    comparison of the function against itself, which two identically empty or
    identically truncated renders would satisfy.
    """
    stack = ResolvedStack(profiles=["ds", "chem"], inline=["umap-learn"])
    expanded = render_requirements_in(stack, config_tree, "main", Variables((), {}))
    assert expanded == render_requirements_in(stack, config_tree, "main", None)
    assert "# Profile: ds" in expanded
    assert "# Profile: chem" in expanded
    assert "umap-learn" in expanded
    assert f"-r {config_tree.env_local_path('main')}" in expanded


def test_rendered_output_never_adds_requirement_lines(config_tree: ConfigRoot):
    # Condition 0 end to end: one stack entry can never become two physical
    # lines in the file uv actually reads, whatever a value expands to.
    config_tree.profile_path("dev").write_text("includes:\n  - -e ${DEV}/mypkg\n")
    stack = ResolvedStack(profiles=["dev"], inline=["-e ${DEV}/other"])
    variables = Variables(declared=("DEV",), values={"DEV": "/home/me/code"})
    text = render_requirements_in(stack, config_tree, "main", variables)
    body = [
        line
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    # Two stack entries, plus the single '-r' include the 'main' fixture's
    # requirements.local.in earns.
    assert len(body) == 3
    assert sum(line.startswith("-r ") for line in body) == 1


def test_render_refuses_hostile_variable_value(config_tree: ConfigRoot):
    # A value with a trailing backslash would turn the entry into a
    # continuation, creating a line-count mismatch or merging two entries.
    config_tree.profile_path("dev").write_text("includes:\n  - -e ${DEV}\n")
    stack = ResolvedStack(profiles=["dev"], inline=[])
    variables = Variables(declared=("DEV",), values={"DEV": "/opt/x\\"})
    with pytest.raises(ConfigError) as excinfo:
        render_requirements_in(stack, config_tree, "main", variables)
    assert "backslash" in excinfo.value.message
