"""Pure renderers that turn resolved config into generated file text.

These functions never write to disk; they return strings. Filesystem writes are
the operations layer's responsibility.
"""

from __future__ import annotations

from uv_stack.config import ConfigRoot
from uv_stack.models import EnvConfig, ResolvedStack
from uv_stack.variables import Variables, expand_all

_HEADER = "# Generated by uv-stack — do not edit."
_EDIT_HINT = (
    "# Edit stack.txt, requirements.local.in, profiles/*.yaml, or bundles/*.yaml instead."
)


def render_requirements_in(
    stack: ResolvedStack,
    config: ConfigRoot,
    env_name: str,
    variables: Variables | None,
) -> str:
    """Render the generated ``requirements.in`` for one environment.

    Each profile's packages are expanded inline — uv cannot read the YAML
    profile files — under a ``# Profile: <name>`` comment. The environment's
    ``requirements.local.in`` is referenced with ``-r`` only if it exists.

    This is the single boundary where ``${NAME}`` references are substituted:
    everything uv-stack stores durably keeps the unexpanded text, and only the
    file uv reads holds machine-specific paths.

    :param stack: The resolved profiles and inline requirements.
    :param config: The config root, for profile and local-additions paths.
    :param env_name: The environment being rendered.
    :param variables: Values to substitute, or ``None`` to leave references
        literal. Required rather than defaulted so a new call site cannot
        silently skip expansion. ``None`` is for callers that only need to know
        the render succeeds — ``stack edit``, which must stay machine-independent.
    :returns: The file contents, newline-terminated.
    :raises ConfigError: When a resolved profile cannot be loaded, which does
        not depend on ``variables`` — the profiles are read either way. And,
        when ``variables`` is supplied, on anything :func:`expand_all` refuses:
        a misplaced reference, an undeclared name, a declared name with no
        value on this machine, or a value whose substitution would change which
        options an entry carries.
    """
    lines = [_HEADER, _EDIT_HINT, ""]

    sections: list[tuple[str, list[str]]] = []
    for name in stack.profiles:
        profile = config.load_profile(name)
        sections.append((f"# Profile: {name}", list(profile.includes)))
    if stack.inline:
        sections.append(("# Inline requirements from bundles/stack", list(stack.inline)))

    if variables is not None:
        # Expanded as one sequence so a single error names every offender in
        # the file rather than only those in the first bad profile.
        flat = expand_all([entry for _, entries in sections for entry in entries], variables)
        cursor = 0
        expanded: list[tuple[str, list[str]]] = []
        for header, entries in sections:
            expanded.append((header, flat[cursor : cursor + len(entries)]))
            cursor += len(entries)
        sections = expanded

    for header, entries in sections:
        lines.append(header)
        lines += entries
        lines.append("")

    local = config.env_local_path(env_name)
    if local.is_file():
        lines.append("# Environment-local additions")
        lines.append(f"-r {local}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def render_environment_yml(env: EnvConfig) -> str:
    """Render a micromamba ``environment.yml`` for a named environment.

    ``conda-forge`` is always the top-priority channel; any channels from the
    env's ``channels.txt`` are appended after it (de-duplicated, so listing
    ``conda-forge`` there does not produce a duplicate). Channel order is
    priority order in conda/mamba, so the first listed wins.

    ``python`` and ``pip`` are always emitted; any ``micromamba.txt`` package
    that repeats them (or repeats another package) is dropped, so a redundant
    entry never produces a duplicate dependency line.

    :param env: The environment config (name, python, channels, packages).
    :returns: File text ending with a trailing newline.
    """
    channels = ["conda-forge"]
    for channel in env.channels:
        if channel not in channels:
            channels.append(channel)

    dependencies = [f"python={env.python}", "pip"]
    seen = {"python", "pip"}
    for pkg in env.micromamba:
        # A package spec's name is the leading token before any version or
        # channel qualifier, so ``pip`` and ``pip==24.0`` collapse to one entry.
        key = pkg.split("=", 1)[0].split("<", 1)[0].split(">", 1)[0].split("::", 1)[-1].strip()
        if key in seen:
            continue
        seen.add(key)
        dependencies.append(pkg)

    lines = [
        _HEADER,
        f"name: {env.name}",
        "channels:",
    ]
    lines += [f"  - {channel}" for channel in channels]
    lines.append("dependencies:")
    lines += [f"  - {dep}" for dep in dependencies]
    return "\n".join(lines) + "\n"
