"""Pure renderers that turn resolved config into generated file text.

These functions never write to disk; they return strings. Filesystem writes are
the operations layer's responsibility.
"""

from __future__ import annotations

from uv_stack.config import ConfigRoot
from uv_stack.models import EnvConfig, ResolvedStack

_HEADER = "# Generated by uv-stack — do not edit."
_EDIT_HINT = (
    "# Edit stack.txt, requirements.local.in, profiles/*.in, or bundles/*.bundle instead."
)


def render_requirements_in(stack: ResolvedStack, config: ConfigRoot, env_name: str) -> str:
    """Render the layered ``requirements.in`` for a named environment.

    Profiles are referenced with ``-r`` so edits to a profile propagate without
    re-rendering. The environment's ``requirements.local.in`` is referenced only
    if it exists.

    :param stack: The resolved stack.
    :param config: The configuration root (for absolute profile/local paths).
    :param env_name: Name of the environment being rendered.
    :returns: File text ending with a trailing newline.
    """
    lines: list[str] = [_HEADER, _EDIT_HINT, ""]

    if stack.profiles:
        lines.append("# Profile requirements")
        lines += [f"-r {config.profile_path(name)}" for name in stack.profiles]
        lines.append("")

    if stack.inline:
        lines.append("# Inline requirements from bundles/stack")
        lines += list(stack.inline)
        lines.append("")

    local = config.env_local_path(env_name)
    if local.is_file():
        lines.append("# Environment-local additions")
        lines.append(f"-r {local}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def render_requirements_flat(stack: ResolvedStack, config: ConfigRoot) -> str:
    """Render a flattened requirements list for ``project init``.

    Each profile's lines are expanded inline so the result is self-contained and
    does not reference files under the config root.

    :param stack: The resolved stack.
    :param config: The configuration root (for loading profile contents).
    :returns: File text ending with a trailing newline.
    """
    lines: list[str] = [_HEADER, ""]

    for name in stack.profiles:
        profile = config.load_profile(name)
        lines.append(f"# Profile: {name}")
        lines += list(profile.requirements)
        lines.append("")

    if stack.inline:
        lines.append("# Inline requirements from bundles/stack")
        lines += list(stack.inline)
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def render_environment_yml(env: EnvConfig) -> str:
    """Render a micromamba ``environment.yml`` for a named environment.

    :param env: The environment config (name, python, micromamba packages).
    :returns: File text ending with a trailing newline.
    """
    lines = [
        _HEADER,
        f"name: {env.name}",
        "channels:",
        "  - conda-forge",
        "dependencies:",
        f"  - python={env.python}",
        "  - pip",
    ]
    lines += [f"  - {pkg}" for pkg in env.micromamba]
    return "\n".join(lines) + "\n"
