"""Pure renderers that turn resolved config into generated file text.

These functions never write to disk; they return strings. Filesystem writes are
the operations layer's responsibility.
"""

from __future__ import annotations

from uv_stack.config import ConfigRoot
from uv_stack.models import EnvConfig, ResolvedStack

_HEADER = "# Generated by uv-stack — do not edit."
_EDIT_HINT = (
    "# Edit stack.txt, requirements.local.in, profiles/*.yaml, or bundles/*.yaml instead."
)


def render_requirements_in(stack: ResolvedStack, config: ConfigRoot, env_name: str) -> str:
    """Render the layered ``requirements.in`` for a named environment.

    Each profile's packages are expanded inline (uv cannot read the YAML
    profile files), under a ``# Profile: <name>`` comment. The environment's
    ``requirements.local.in`` is referenced with ``-r`` only if it exists.

    :param stack: The resolved stack.
    :param config: The configuration root (for loading profiles and the local path).
    :param env_name: Name of the environment being rendered.
    :returns: File text ending with a trailing newline.
    """
    lines: list[str] = [_HEADER, _EDIT_HINT, ""]

    for name in stack.profiles:
        profile = config.load_profile(name)
        lines.append(f"# Profile: {name}")
        lines += list(profile.includes)
        lines.append("")

    if stack.inline:
        lines.append("# Inline requirements from bundles/stack")
        lines += list(stack.inline)
        lines.append("")

    local = config.env_local_path(env_name)
    if local.is_file():
        lines.append("# Environment-local additions")
        lines.append(f"-r {local}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def render_requirements_flat(stack: ResolvedStack, config: ConfigRoot) -> str:
    """Render a flattened requirements list for ``project init``.

    Each profile's lines are expanded inline so the result is self-contained and
    does not reference files under the config root.

    :param stack: The resolved stack.
    :param config: The configuration root (for loading profile contents).
    :returns: File text ending with a trailing newline.
    """
    lines: list[str] = [_HEADER, ""]

    for name in stack.profiles:
        profile = config.load_profile(name)
        lines.append(f"# Profile: {name}")
        lines += list(profile.includes)
        lines.append("")

    if stack.inline:
        lines.append("# Inline requirements from bundles/stack")
        lines += list(stack.inline)
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def render_environment_yml(env: EnvConfig) -> str:
    """Render a micromamba ``environment.yml`` for a named environment.

    ``conda-forge`` is always the top-priority channel; any channels from the
    env's ``channels.txt`` are appended after it (de-duplicated, so listing
    ``conda-forge`` there does not produce a duplicate). Channel order is
    priority order in conda/mamba, so the first listed wins.

    ``python`` and ``pip`` are always emitted; any ``micromamba.txt`` package
    that repeats them (or repeats another package) is dropped, so a redundant
    entry never produces a duplicate dependency line.

    :param env: The environment config (name, python, channels, packages).
    :returns: File text ending with a trailing newline.
    """
    channels = ["conda-forge"]
    for channel in env.channels:
        if channel not in channels:
            channels.append(channel)

    dependencies = [f"python={env.python}", "pip"]
    seen = {"python", "pip"}
    for pkg in env.micromamba:
        # A package spec's name is the leading token before any version or
        # channel qualifier, so ``pip`` and ``pip==24.0`` collapse to one entry.
        key = pkg.split("=", 1)[0].split("<", 1)[0].split(">", 1)[0].split("::", 1)[-1].strip()
        if key in seen:
            continue
        seen.add(key)
        dependencies.append(pkg)

    lines = [
        _HEADER,
        f"name: {env.name}",
        "channels:",
    ]
    lines += [f"  - {channel}" for channel in channels]
    lines.append("dependencies:")
    lines += [f"  - {dep}" for dep in dependencies]
    return "\n".join(lines) + "\n"
